name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install libgtk-4-dev libadwaita-1-dev 
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint PyGObject PyGObject-stubs
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
